AllCops:
  TargetRubyVersion: 3.3
  Exclude:
  - 'spec/**/*'
  - 'bin/*'

Bundler/OrderedGems:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'lib/tasks/**/*'

Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Metrics/MethodLength:
  Enabled: false

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Style/FrozenStringLiteralComment:
  Enabled: true

Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/OptionalBooleanParameter:
  Enabled: false

Layout/EmptyLines:
  Enabled: true

Metrics/LineLength:
  Max: 120
  IgnoreCopDirectives: True
