# coding: utf-8
lib = File.expand_path('../lib', __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)
require 'poparser/version'

Gem::Specification.new do |spec|
  spec.name          = "PoParser"
  spec.version       = PoParser::VERSION
  spec.authors       = ["Arash Mousavi"]
  spec.email         = ["mousavi.arash@gmail.com"]
  spec.summary       = %q{A PO file parser (localization files generated by Gettext)}
  spec.description   = %q{A PO file parser}
  spec.homepage      = ""
  spec.license       = "MIT"

  spec.files         = `git ls-files`.split($/)
  spec.executables   = spec.files.grep(%r{^bin/}) { |f| File.basename(f) }
  spec.test_files    = spec.files.grep(%r{^(test|spec|features)/})
  spec.require_paths = ["lib"]

  # Runtime deps
  spec.add_runtime_dependency "parslet"

  # Development deps
  spec.add_development_dependency "bundler", "~> 1.5"
  spec.add_development_dependency "rake"
  spec.add_development_dependency "rspec", "~> 2.14"
  spec.add_development_dependency "guard-rspec"
  spec.add_development_dependency "pry-debugger"
  spec.add_development_dependency "awesome_print"
end
